/**
 * Auto-generated by CMS
 * 2026-06-15T14:20:28.112Z
 */
const SITE_CONFIG = {
    "photographer": {
        "name": "杉果派",
        "nameEn": "SgLxQ",
        "tagline": "新手摄影师 · 摸鱼程序员 "
    },
    "hero": {
        "image": "https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=1920&q=85",
        "scrollHint": "向下探索"
    },
    "works": {
        "heading": "用镜头讲述未被言说的故事",
        "items": [
            {
                "title": "马倩倩",
                "category": "人像摄影",
                "image": "https://img.sglxq.cn/img/mqq/PLQ_3883.jpg",
                "layout": "tall",
                "images": [
                    "https://img.sglxq.cn/img/mqq/老马-01.png",
                    "https://img.sglxq.cn/img/mqq/老马-02.png",
                    "https://img.sglxq.cn/img/mqq/老马-03.png",
                    "https://img.sglxq.cn/img/mqq/老马-04.png",
                    "https://img.sglxq.cn/img/mqq/老马-05.png",
                    "https://img.sglxq.cn/img/mqq/PLQ_3828.jpg",
                    "https://img.sglxq.cn/img/mqq/PLQ_3829.jpg",
                    "https://img.sglxq.cn/img/mqq/PLQ_3850.jpg",
                    "https://img.sglxq.cn/img/mqq/PLQ_3851.jpg",
                    "https://img.sglxq.cn/img/mqq/PLQ_3852.jpg",
                    "https://img.sglxq.cn/img/mqq/PLQ_3854.jpg",
                    "https://img.sglxq.cn/img/mqq/PLQ_3883.jpg",
                    "https://img.sglxq.cn/img/mqq/PLQ_3885.jpg",
                    "https://img.sglxq.cn/img/mqq/PLQ_3886.jpg",
                    "https://img.sglxq.cn/img/mqq/PLQ_3896.jpg"
                ]
            }
        ]
    },
    "about": {
        "visible": false,
        "role": "摄影师 / 视觉艺术家",
        "bio": [
            "从事摄影创作十余年，专注于通过镜头捕捉人与环境之间微妙的情感联结。我的作品试图在光影交错之间，找到那些容易被忽视的真实瞬间。",
            "曾为《Vogue》《国家地理》《时尚芭莎》等刊物拍摄专题，作品在国内外多次展出。我相信最好的照片不是拍出来的，而是与眼前的景物流淌在一起的。"
        ],
        "stats": [
            {
                "label": "经验",
                "value": "12 年"
            },
            {
                "label": "项目",
                "value": "200+"
            },
            {
                "label": "获奖",
                "value": "15 项"
            }
        ]
    },
    "aboutImage": "",
    "social": {
        "links": [
            {
                "name": "抖音",
                "url": " https://v.douyin.com/jo30qS_j0l8"
            }
        ]
    },
    "footer": {
        "copyright": "© 2026 ·SgLxQ · 版权所有"
    },
    "theme": {
        "active": "theme-example"
    }
};
